# Generated by Django 3.2.23 on 2023-11-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='agent',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
