# Generated by Django 3.2.23 on 2023-11-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.agent'),
            preserve_default=False,
        ),
    ]
